version: '{branch}-{build}'
branches:
  only:
  - master
init:
  - ps: (get-psprovider 'FileSystem').Home = $(pwd)
  - ps: Install-PackageProvider Nuget -Force
  - ps: Install-Module -Name Pester -Repository PSGallery -Force
install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: $env:SCOOP_HOME = resolve-path (split-path (split-path (scoop which scoop)))
build: off
test_script:
  - ps: $result = invoke-pester -path test/ -outputfile TestResults.xml -outputformat NUnitXML -passthru; $env:failedcount = $result.failedcount
  - ps: (new-object net.webclient).uploadfile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (resolve-path ./TestResults.xml))
  - ps: if($env:failedcount -gt 0) { exit $env:failedcount }
